---
# handlers file for ansible-role-rhsso
  - name: start and enable rhsso
    service:
      name: "rhsso@{{ rhsso_mode }}.service"
      state: started
      enabled: yes
  
  - name: restart rhsso
    service:
      name: "rhsso@{{ rhsso_mode }}.service"
      state: restarted